version: 2

models:
  - name: stg_trips_unified
    description: "Unified staging table combining Yellow and Green taxi trips"
    columns:
      - name: service_type
        description: "Type of taxi service (yellow or green)"
        tests:
          - not_null
          - accepted_values:
              values: ['yellow', 'green']

      - name: pickup_datetime
        description: "Timestamp when the meter was engaged"
        tests:
          - not_null

      - name: dropoff_datetime
        description: "Timestamp when the meter was disengaged"
        tests:
          - not_null

      - name: trip_distance
        description: "Trip distance in miles"
        tests:
          - not_null

      - name: total_amount
        description: "Total amount charged to passengers"
        tests:
          - not_null

      - name: pulocationid
        description: "Pickup location ID"
        tests:
          - not_null

      - name: dolocationid
        description: "Dropoff location ID"
        tests:
          - not_null
