# Mage configuration for NYC Taxi project
version: 0.1.1

default:
  # Snowflake connection for data loading
  SNOWFLAKE:
    connector_type: snowflake
    account: "{{ env_var('SNOWFLAKE_ACCOUNT') }}"
    user: "{{ env_var('SNOWFLAKE_USER') }}"
    password: "{{ env_var('SNOWFLAKE_PASSWORD') }}"
    database: "{{ env_var('SNOWFLAKE_DATABASE') }}"
    schema: raw
    warehouse: "{{ env_var('SNOWFLAKE_WAREHOUSE') }}"
    role: "{{ env_var('SNOWFLAKE_ROLE') }}"

  # dbt configuration
  DBT:
    project_path: /home/src/dbt_nyc_taxi
    profiles_dir: /home/src/dbt_nyc_taxi
    target: dev