name: 'nyc_taxi'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'nyc_taxi'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  nyc_taxi:
    # Config for raw (bronze) models
    raw:
      +materialized: table
      +schema: raw
    # Config for silver models
    silver:
      +materialized: table
      +schema: silver
    # Config for gold models (marts)
    gold:
      +materialized: table
      +schema: gold

vars:
  # Define variables that can be used across the project
  start_date: '2015-01-01'
  end_date: '2025-12-31'